name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DISPLAY: :99
  WDM_GITHUBTOKEN: ${{ secrets.WDM_GITHUBTOKEN }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 11 ]
    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Start Xvfb
      run: Xvfb :99 &
    - name: Run tests
      uses: nick-invision/retry@v2.7.1
      with:
        timeout_minutes: 60
        max_attempts: 3
        command: mvn -B test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: txt-files-${{ matrix.os }}
        path: |
          *.txt
